#!/bin/bash

if [[ $1 == 'dims' ]]; then
	echo $1
elif [[ $1 == 'transpose' ]]; then
	echo $1
elif [[ $1 == 'mean' ]]; then
	echo $1
elif [[ $1 == 'add' ]]; then
	echo $1
elif [[ $1 == 'multiply' ]]; then 
	echo $1
fi

if [[ $1 != '' ]]; then
	echo "You entered $1"
else
	echo "You didn't enter anything"
fi 
